"""Add fraud flag fields to transactions

Revision ID: 0869bf3e2abc
Revises: 865a6701f924
Create Date: 2026-09-01 00:56:55.594393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0869bf3e2abc'
down_revision: Union[str, None] = '865a6701f924'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('is_flagged', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('transactions', sa.Column('flag_reasons', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'flag_reasons')
    op.drop_column('transactions', 'is_flagged')
    # ### end Alembic commands ###
