"""Add KYC submissions and user kyc_status

Revision ID: 0f53cfcf63bd
Revises: 99195ac58b68
Create Date: 2026-08-26 09:24:40.963340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f53cfcf63bd'
down_revision: Union[str, None] = '99195ac58b68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
