"""Add fixed deposits table

Revision ID: 28fc9a3e0b8d
Revises: b1df20c10912
Create Date: 2026-08-25 09:36:16.713113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28fc9a3e0b8d'
down_revision: Union[str, None] = 'b1df20c10912'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fixed_deposits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('principal_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('interest_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('term_days', sa.Integer(), nullable=False),
    sa.Column('payout_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('matures_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('matured_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fixed_deposits_id'), 'fixed_deposits', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fixed_deposits_id'), table_name='fixed_deposits')
    op.drop_table('fixed_deposits')
    # ### end Alembic commands ###
