"""Add KYC submissions and user kyc_status

Revision ID: 29f5edf179be
Revises: 0f53cfcf63bd
Create Date: 2026-08-26 10:02:37.089355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29f5edf179be'
down_revision: Union[str, None] = '0f53cfcf63bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
