"""Add currency and exchange rate to transactions

Revision ID: 62dc3473b42a
Revises: cfa2c7f1fb94
Create Date: 2026-08-11 09:53:11.594337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62dc3473b42a'
down_revision: Union[str, None] = 'cfa2c7f1fb94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('currency', sa.String(length=10), nullable=False))
    op.add_column('transactions', sa.Column('exchange_rate', sa.Numeric(precision=20, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'exchange_rate')
    op.drop_column('transactions', 'currency')
    # ### end Alembic commands ###
