"""Add status to transactions for admin approval

Revision ID: 782d8b1c1e12
Revises: bdf3bcbaf99c
Create Date: 2026-08-13 15:21:46.421043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '782d8b1c1e12'
down_revision: Union[str, None] = 'bdf3bcbaf99c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
