"""Add KYC submissions and user kyc_status

Revision ID: 865a6701f924
Revises: 29f5edf179be
Create Date: 2026-08-26 10:21:18.133454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '865a6701f924'
down_revision: Union[str, None] = '29f5edf179be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kyc_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('full_legal_name', sa.String(length=150), nullable=False),
    sa.Column('date_of_birth', sa.String(length=10), nullable=False),
    sa.Column('id_type', sa.String(length=30), nullable=False),
    sa.Column('id_number', sa.String(length=50), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kyc_submissions_id'), 'kyc_submissions', ['id'], unique=False)
    op.add_column('users', sa.Column('kyc_status', sa.String(length=20), nullable=False, server_default='unverified'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'kyc_status')
    op.drop_index(op.f('ix_kyc_submissions_id'), table_name='kyc_submissions')
    op.drop_table('kyc_submissions')
    # ### end Alembic commands ###
