"""Add status to transactions

Revision ID: bdf3bcbaf99c
Revises: 62dc3473b42a
Create Date: 2026-08-13 09:40:09.402365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdf3bcbaf99c'
down_revision: Union[str, None] = '62dc3473b42a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('status', sa.String(length=20), nullable=False, server_default='approved'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'status')
    # ### end Alembic commands ###
