"""Add paystack payments table

Revision ID: cbab56513ca0
Revises: 0869bf3e2abc
Create Date: 2026-09-01 03:06:23.930470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbab56513ca0'
down_revision: Union[str, None] = '0869bf3e2abc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paystack_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paystack_payments_id'), 'paystack_payments', ['id'], unique=False)
    op.create_index(op.f('ix_paystack_payments_reference'), 'paystack_payments', ['reference'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_paystack_payments_reference'), table_name='paystack_payments')
    op.drop_index(op.f('ix_paystack_payments_id'), table_name='paystack_payments')
    op.drop_table('paystack_payments')
    # ### end Alembic commands ###
